# Generated by Django 5.0.1 on 2024-04-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipes',
            name='receipe_image',
            field=models.ImageField(upload_to='receipe'),
        ),
    ]
